# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptext', models.CharField(max_length=144)),
                ('cdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
